/*
 * Copyright (c) 2016 PrivatBank IT <acsk@privatbank.ua>. All rights reserved.
 * Redistribution and modifications are permitted subject to BSD license.
 */

#ifndef CRYPTONITE_STORAGE_ERRORS_H_
#define CRYPTONITE_STORAGE_ERRORS_H_

#include "pkix_errors.h"

/** Коди помилок. */

#define RET_STORAGE_ERROR_NAME_CODE           0x0200

#define RET_STORAGE_ERROR                     (RET_STORAGE_ERROR_NAME_CODE | 0x00000004)

#define RET_STORAGE_INVALID_STORAGE           (RET_STORAGE_ERROR_NAME_CODE | 0x0000000a)
#define RET_STORAGE_INVALID_PASSWORD          (RET_STORAGE_ERROR_NAME_CODE | 0x0000000b)
#define RET_STORAGE_EMPTY_PASSWORD            (RET_STORAGE_ERROR_NAME_CODE | 0x0000000c)
#define RET_STORAGE_CERT_NOT_FOUND            (RET_STORAGE_ERROR_NAME_CODE | 0x0000000d)

#define RET_STORAGE_NOT_CORRESPOND_CERT_ERROR             (RET_STORAGE_ERROR_NAME_CODE | 0x0000000f)
#define RET_STORAGE_UNSUPPORTED_KEY_DERIVATION_FUNC_ALG   (RET_STORAGE_ERROR_NAME_CODE | 0x00000010)
#define RET_STORAGE_UNSUPPORTED_CONTENT_ENC_ALG           (RET_STORAGE_ERROR_NAME_CODE | 0x00000011)
#define RET_STORAGE_UNSUPPORTED_TYPE                      (RET_STORAGE_ERROR_NAME_CODE | 0x00000012)
#define RET_STORAGE_UNSUPPORTED_CINFO_TYPE                (RET_STORAGE_ERROR_NAME_CODE | 0x00000013)
#define RET_STORAGE_UNSUPPORTED_SAFE_BAG_ALG              (RET_STORAGE_ERROR_NAME_CODE | 0x00000014)
#define RET_STORAGE_UNSUPPORTED_CERT_BAG_ALG              (RET_STORAGE_ERROR_NAME_CODE | 0x00000015)
#define RET_STORAGE_UNSUPPORTED_HMAC_ID                   (RET_STORAGE_ERROR_NAME_CODE | 0x00000016)
#define RET_STORAGE_UNSUPPORTED_ENC_PRIV_KEY_ALG          (RET_STORAGE_ERROR_NAME_CODE | 0x00000017)
#define RET_STORAGE_UNSUPPORTED_ENC_SCHEME_ALG            (RET_STORAGE_ERROR_NAME_CODE | 0x00000018)
#define RET_STORAGE_UNSUPPORTED_KDF_PARAMS_ALG            (RET_STORAGE_ERROR_NAME_CODE | 0x00000019)
#define RET_STORAGE_UNSUPPORTED_ENC_ALG                   (RET_STORAGE_ERROR_NAME_CODE | 0x0000001a)
#define RET_STORAGE_UNSUPPORTED_PRIV_KEY_TYPE             (RET_STORAGE_ERROR_NAME_CODE | 0x0000001b)
#define RET_STORAGE_INVALID_KEP_KEY_ATTR                  (RET_STORAGE_ERROR_NAME_CODE | 0x0000001c)


#define RET_STORAGE_CMS_INVALID_DATA          (RET_STORAGE_ERROR_NAME_CODE | 0x000000c0)

#define RET_STORAGE_NO_KEY                    (RET_STORAGE_ERROR_NAME_CODE | 0x000000a0)
#define RET_STORAGE_BAD_KEY                   (RET_STORAGE_ERROR_NAME_CODE | 0x000000a1)
#define RET_STORAGE_MAC_VERIFY_ERROR          (RET_STORAGE_ERROR_NAME_CODE | 0x000000a2)
#define RET_STORAGE_BAD_PARAMS                (RET_STORAGE_ERROR_NAME_CODE | 0x000000a3)
#define RET_STORAGE_INVALID_KEY_PASSWORD      (RET_STORAGE_ERROR_NAME_CODE | 0x000000a4)

#define RET_STORAGE_BAD_SUBJ_KEY_ID           (RET_STORAGE_ERROR_NAME_CODE | 0x000000a4)
#define RET_STORAGE_UNSUP_SEARCH_CERT_TYPE    (RET_STORAGE_ERROR_NAME_CODE | 0x000000a5)
#define RET_STORAGE_INVALID_SEARCH_RESPONSE   (RET_STORAGE_ERROR_NAME_CODE | 0x000000a6)
#define RET_STORAGE_NO_CERT_FOUND_RESPONSE    (RET_STORAGE_ERROR_NAME_CODE | 0x000000a7)
#define RET_STORAGE_FILE_OPEN_ERROR           (RET_STORAGE_ERROR_NAME_CODE | 0x000000a8)
#define RET_STORAGE_FILE_READ_ERROR           (RET_STORAGE_ERROR_NAME_CODE | 0x000000a9)
#define RET_STORAGE_FILE_WRITE_ERROR          (RET_STORAGE_ERROR_NAME_CODE | 0x000000aa)
#define RET_STORAGE_FILE_GET_SIZE_ERROR       (RET_STORAGE_ERROR_NAME_CODE | 0x000000ab)
#define RET_STORAGE_DIR_OPEN_ERROR            (RET_STORAGE_ERROR_NAME_CODE | 0x000000ac)
#define RET_STORAGE_KEY_ALREADY_EXIST         (RET_STORAGE_ERROR_NAME_CODE | 0x000000ad)
#define RET_STORAGE_UNSUPPORTED_MAC           (RET_STORAGE_ERROR_NAME_CODE | 0x000000ae)
#define RET_STORAGE_KEY_NOT_SELECTED          (RET_STORAGE_ERROR_NAME_CODE | 0x000000af)



#endif
